# yamllint disable rule:line-length
---
network_ipv6_enable: True
ssh_server_password_login: True
ssh_client_password_login: True
ssh_allow_groups: "ssh"
ssh_listen_to:
  - ssh.goodforpocin.tech
sysctl_config:
  net.ipv4.conf.all.arp_announce: 2
  net.ipv4.conf.all.arp_ignore: 1
  net.ipv4.conf.all.rp_filter: 1
  net.ipv4.conf.default.rp_filter: 1
  net.ipv4.icmp_echo_ignore_broadcasts: 1
  net.ipv4.icmp_ignore_bogus_error_responses: 1
  net.ipv4.icmp_ratelimit: 100
  net.ipv4.icmp_ratemask: 88089
  net.ipv4.ip_forward: 1
  net.ipv4.tcp_rfc1337: 1
  net.ipv4.tcp_timestamps: 0
  net.ipv6.conf.all.accept_ra: 0
  net.ipv6.conf.all.disable_ipv6: 0
  net.ipv6.conf.all.forwarding: 1
  net.ipv6.conf.default.accept_ra: 0
  net.ipv6.conf.default.disable_ipv6: 0
  net.ipv6.conf.lo.disable_ipv6: 0
firewall_allowed_tcp_ports:
  - "22"    # SSH support.
  - "80"    # HTTP support.
  - "443"   # HTTPS support.
  - "60002" # Mosh support.
firewall_disable_firewalld: False
firewall_disable_ufw: True
