---
language: ruby
env:
  - ENV=test
before_script:
  - bundle config --delete without
  - bundle install --verbose
script:
  - bundle exec rake test
deploy:
  - provider: script
    script: scripts/deploy prod
    on:
      branch: master
  - provider: script
    script: scripts/deploy staging
    on:
      branch: develop

notifications:
  webhooks:
    urls:
      - https://webhooks.gitter.im/e/d9bba348105e7154a7b6
    on_success: always
    on_failure: always
    on_start: always
