---
language: ruby
before_script:
  - bundle config --delete without
  - bundle install --verbose
script:
  - bundle exec rake test

notifications:
  webhooks:
    urls:
      - https://webhooks.gitter.im/e/d9bba348105e7154a7b6
    on_success: always
    on_failure: always
    on_start: always
