# vim: set ft=yaml :
#
# This file serves as a development representation of what GoodForPoc looks
# like.
#
---
version: '2.1'
services:
  api:
    build: .
    environment:
      - "APP_PORT=9292"
      - "APP_ENV=development"
      - "BUNDLE_CACHE=/var/cache/app-gems"
    ports:
      - '${API_PORT-9292}:9292'
    volumes:
      - '.:/app'
      - 'api_ruby_cache:/var/cache/app-gems'
      - 'api_ruby_gems:/usr/local/bundle'
volumes:
  api_ruby_gems:
    driver: local
  api_ruby_cache:
    driver: local
