# vim: set ft=yaml :
#
# This file serves as a development representation of what GoodForPoc looks
# like.
#
---
version: '2'
services:
  api:
    build: .
    env_file: .env.api
    links:
      - db:db
      - cache:cache
