# vim: set ft=yaml :
#
# This file serves as a development representation of what GoodForPoc looks
# like.
#
---
version: '2.1'
services:
  api:
    build: .
    environment:
      - "RACK_ENV=development"
      - "API_PORT=9292"
      - "BUNDLE_FROZEN="
      - "BUNDLE_CACHE=/var/cache/app-gems"
    ports:
      - '${API_PORT-9292}:9292'
    volumes:
      - '.:/app'
      - 'api_ruby_gems:/var/cache/app-gems'
volumes:
  api_ruby_gems:
    driver: local
