# vim: set ft=yaml :
#
# This file serves as a development representation of what GoodForPoc looks
# like.
#
---
version: '2.1'
services:
  psql:
    image: postgres:alpine
    hostname: data
    environment:
      - 'POSTGRES_USER=g4poc'
      - 'POSTGRES_PASSWORD="*(g4p0c_"'
    volumes:
      - 'api_data:/var/lib/postgresql'
  mock_graphql_api:
    build: ./mock-api
    hostname: mock_graphql
    command: serve-foreground
    environment:
      - 'DEBUG="*"'
  api:
    build: .
    environment:
      - 'PORT=9292'
      - 'RACK_ENV=development'
      - 'DATABASE_URL=psql://data:5432'
      - 'APP_DIR=/app'
      - 'MOCK_GRAPHQL_SERVER_HOST=http://mock_graphql_api:3000'
    depends_on:
      - psql
      - mock_graphql_api
    links:
      - psql
      - mock_graphql_api
    ports:
      - '${PORT-9292}:9292'
    volumes:
      - '.:/app'
volumes:
  api_data:
    driver: local
