# vim: set ft=yaml :
#
# This file serves as a development representation of what GoodForPoc looks
# like.
#
---
version: '2.1'
services:
  psql:
    image: postgres:alpine
    environment:
      - 'POSTGRES_USER=g4poc'
      - 'POSTGRES_PASSWORD="*(g4p0c_"'
    volumes:
      - 'api_data:/var/lib/postgresql'
  mock_graphql_api:
    build: ./mock-api
    hostname: mock_graphql
  api:
    build: .
    environment:
      - 'PORT=9292'
      - 'RACK_ENV=development'
      - 'BUNDLE_CACHE=/app/vendor/cache'
      - 'DATABASE_URL=psql://psql:5432'
      - 'APP_DIR=/app'
    depends_on:
      - psql
      - mock_graphql_api
    ports:
      - '${PORT-9292}:9292'
    volumes:
      - '.:/app'
      - 'api_ruby_cache:/app/vendor/cache'
      - 'api_ruby_gems:/app/vendor/bundle'
volumes:
  api_ruby_gems:
    driver: local
  api_ruby_cache:
    driver: local
  api_data:
    driver: local
